//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspAssignmnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobId { get; set; }
        public string JobName { get; set; }
        public string JobDescription { get; set; }
        public string JobLocation { get; set; }
        public string JobPosiotion { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<System.DateTime> JobPublishedDate { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
